language: go

go:
- 1.x

os:
  - linux
  - windows

branches:
  only:
    - master
    - develop
    - /^feature\/travis\/.+$/ # feature/travis/*
    - /^fix\/travis\/.+$/ # fix/travis/*

install:
  - go get -d -u github.com/golang/dep
  - go install github.com/golang/dep/cmd/dep
  - go mod download
  - ./test install

script: ./test --scripted
